# Gradient Descent

In [1]:
import torch
import torch.nn.functional as F

In [13]:
target = torch.FloatTensor([[.1, .2, .3],
                            [.4, .5, .6],
                            [.7, .8, .9]])

In [14]:
x = torch.rand_like(target)
# This means the final scalar will be differentiate by x.
x.requires_grad = True
# You can get gradient of x, after differentiation.

x

tensor([[0.1282, 0.2342, 0.0170],
        [0.2083, 0.7374, 0.9349],
        [0.5477, 0.1604, 0.8555]], requires_grad=True)

In [15]:
loss = F.mse_loss(x, target)

loss

tensor(0.0802, grad_fn=<MseLossBackward>)

In [16]:
threshold = 1e-5
learning_rate = 1.
iter_cnt = 0

while loss > threshold:
    iter_cnt += 1
    
    loss.backward() # Calculate gradients.

    x = x - learning_rate * x.grad  ## x를 업데이트
    # 여기서 x.grad가 loss.backward
    
    # You don't need to aware this now.
    x.detach_()
    x.requires_grad_(True)
    
    loss = F.mse_loss(x, target)
    
    print('%d-th Loss: %.4e' % (iter_cnt, loss))
    print(x)

1-th Loss: 4.8501e-02
tensor([[0.1219, 0.2266, 0.0799],
        [0.2509, 0.6846, 0.8605],
        [0.5815, 0.3025, 0.8654]], requires_grad=True)
2-th Loss: 2.9340e-02
tensor([[0.1171, 0.2207, 0.1288],
        [0.2840, 0.6436, 0.8026],
        [0.6079, 0.4131, 0.8731]], requires_grad=True)
3-th Loss: 1.7749e-02
tensor([[0.1133, 0.2161, 0.1668],
        [0.3098, 0.6117, 0.7576],
        [0.6283, 0.4991, 0.8791]], requires_grad=True)
4-th Loss: 1.0737e-02
tensor([[0.1103, 0.2125, 0.1964],
        [0.3298, 0.5869, 0.7226],
        [0.6443, 0.5659, 0.8837]], requires_grad=True)
5-th Loss: 6.4952e-03
tensor([[0.1080, 0.2097, 0.2194],
        [0.3454, 0.5676, 0.6953],
        [0.6566, 0.6180, 0.8873]], requires_grad=True)
6-th Loss: 3.9292e-03
tensor([[0.1062, 0.2076, 0.2373],
        [0.3576, 0.5525, 0.6741],
        [0.6663, 0.6584, 0.8902]], requires_grad=True)
7-th Loss: 2.3769e-03
tensor([[0.1049, 0.2059, 0.2513],
        [0.3670, 0.5409, 0.6577],
        [0.6738, 0.6899, 0.8923]], requi