# PyTorch Tensor

In [2]:
import torch

## Tensor Allocation

In [2]:
ft = torch.FloatTensor([[1, 2],
                        [3, 4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [3]:
lt = torch.LongTensor([[1, 2],
                       [3, 4]])
lt
# 롱텐서 는 인티저

tensor([[1, 2],
        [3, 4]])

In [6]:
bt = torch.ByteTensor([[1, 0],
                       [0, 1]])
bt
# 얘는 0 혹은 1
# 얘전에는 예로 불리안 했었는데 요새는
# 불리안 텐서로 한다는데 뭐지

blt = torch.BoolTensor([[1, 0],
                         [0, 1]])
blt

tensor([[ True, False],
        [False,  True]])

In [5]:
x = torch.FloatTensor(3, 2) # 이렇게 하면 랜덤값
x

tensor([[8.4490e-39, 1.0010e-38],
        [9.6429e-39, 8.4490e-39],
        [9.2755e-39, 9.1837e-39]])

## NumPy Compatibility

In [6]:
import numpy as np

# Define numpy array.
x = np.array([[1, 2],
              [3, 4]])
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [7]:
x = torch.from_numpy(x) # 넘파이와 파이토치 사이 왔다 갔다 가능
print(x, type(x))

tensor([[1, 2],
        [3, 4]], dtype=torch.int32) <class 'torch.Tensor'>


In [8]:
x = x.numpy() # 넘파이와 파이토치 사이 왔다 갔다 가능
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


## Tensor Type-casting
- float는 float끼리 long 은 long끼리 연산해야됨
- 따라서 아래처럼 서로 바꿔주고 연산

In [9]:
ft.long()

tensor([[1, 2],
        [3, 4]])

In [10]:
lt.float()

tensor([[1., 2.],
        [3., 4.]])

In [11]:
torch.FloatTensor([1, 0]).byte()

tensor([1, 0], dtype=torch.uint8)

## Get Shape

In [12]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])

Get tensor shape.

In [14]:
print(x.size())
print(x.shape)

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


Get number of dimensions in the tensor.

In [15]:
print(x.dim())
print(len(x.size()))

3
3


Get number of elements in certain dimension of the tensor.

In [19]:
print(x.size(0))
print(x.shape[1])

3
2


Get number of elements in the last dimension.

In [17]:
print(x.size(-1))
print(x.shape[-1])

2
2
