# PyTorch AutoGrad

- requires_grad 를 True로 하면 해당 탠서에서 이루어지는 연산들을 추적(track)함

- 연산이 완료 되면 .backward() 메소드를 호출하여 모든 gradient를 자동 계산

- tensor에 대한 gradient는 .grad속성에 누적됨

- .detach()를 호출하여 더이상 추적하지 않도록 할 수 있음

- 즉, 내용물은 같지만 requires_grad가 다른 새로운 텐서 만들 수 있음.

In [1]:
import torch

In [14]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]]).requires_grad_(True) # 그레디언트가 필요하니? 얘로 미분할거니?

x

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [15]:
x1 = x + 2
x2 = x - 2
x3 = x1 * x2
y = x3.sum()

print(x1)
print(x2)
print(x3)
print(y)

tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>)
tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)
tensor([[-3.,  0.],
        [ 5., 12.]], grad_fn=<MulBackward0>)
tensor(14., grad_fn=<SumBackward0>)


In [16]:
y.backward() # y는 스칼라
# backward requires_grad=True 인 애들을 다 미분한다. 

$$
\begin{gathered}
x=\begin{bmatrix}
x_{(1,1)} & x_{(1,2)} \\
x_{(2,1)} & x_{(2,2)}
\end{bmatrix}\\
\\
x_1=x+2 \\
x_2=x-2 \\
\\
\begin{aligned}
x_3&=x_1\times{x_2} \\
&=(x+2)(x-2) \\
&=x^2-4
\end{aligned} \\
\\
\begin{aligned}
y&=\text{sum}(x_3) \\
&=x_{3,(1,1)}+x_{3,(1,2)}+x_{3,(2,1)}+x_{3,(2,2)}
\end{aligned} \\
\\
\text{x.grad}=\begin{bmatrix}
\frac{\partial{y}}{\partial{x_{(1,1)}}} & \frac{\partial{y}}{\partial{x_{(1,2)}}} \\
\frac{\partial{y}}{\partial{x_{(2,1)}}} & \frac{\partial{y}}{\partial{x_{(2,2)}}}
\end{bmatrix} \\
\\
\frac{dy}{dx}=2x
\end{gathered}
$$

In [17]:
print(x.grad) # backward에 저장된 x를 미분?????

tensor([[2., 4.],
        [6., 8.]])


In [18]:
print(x)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [21]:
print(x3.grad)

None
<ipython-input-21-e91536e93bb3>:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  print(x3.grad)


In [19]:
x3.numpy()

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

In [22]:
x3.detach_().numpy()

array([[-3.,  0.],
       [ 5., 12.]], dtype=float32)

In [2]:
import torch

In [7]:
x = torch.FloatTensor([[1, 1],
                       [1, 1]]).requires_grad_(True)

In [8]:
x1 = x ** 2
x2 = x1 * 3
x3 = x2 ** 3
y = x3.sum()

print(x1)
print(x2)
print(x3)
print(y)

tensor([[1., 1.],
        [1., 1.]], grad_fn=<PowBackward0>)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<MulBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<PowBackward0>)
tensor(108., grad_fn=<SumBackward0>)


In [9]:
y.backward()

In [10]:
print(x.grad) 

tensor([[162., 162.],
        [162., 162.]])
