# PyTorch Tensor Operations

In [1]:
import torch

## Arithmetic Element-wise Operations
- 그냥 각각 대응하는애들 끼리 계산 (Element-wise)

In [2]:
a = torch.FloatTensor([[1, 2],
                       [3, 4]])
b = torch.FloatTensor([[2, 2],
                       [3, 3]])

In [15]:
a.shape
c = torch.BoolTensor([1, 0])
c

tensor([ True, False])

In [6]:
a + b

tensor([[3., 4.],
        [6., 7.]])

In [7]:
a - b

tensor([[-1.,  0.],
        [ 0.,  1.]])

In [8]:
a * b

tensor([[ 2.,  4.],
        [ 9., 12.]])

In [9]:
a / b

tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])

In [10]:
a == b

tensor([[False,  True],
        [ True, False]])

In [16]:
a != b

tensor([[ True, False],
        [False,  True]])

In [17]:
a ** b

tensor([[ 1.,  4.],
        [27., 64.]])

## Inplace Operations

In [18]:
print(a)
print(a.mul(b))
print(a)
print(a.mul_(b)) # 이게 인플레이스 오퍼레이션, a곱하기 b의 결과를 a에 할당
# 근데 머 굳이 쓸 필요는 없다고 함
print(a)

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])


## Sum, Mean (Dimension Reducing Operations)

In [19]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])

In [20]:
print(x.sum())
print(x.mean())

tensor(10.)
tensor(2.5000)


In [23]:
# 특정 디멘젼을 지정, 없어질 디멘젼 지정
print(x.sum(dim=0))
print(x.sum(dim=1))
print(x.sum(dim=-1))

tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


## Broadcast in Operations
- 다른 디멘젼에서 계산

What we did before,

In [24]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[4, 8]])

print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([1, 2])


In [25]:
z = x + y
print(z)
print(z.size())

tensor([[ 5., 10.]])
torch.Size([1, 2])


Broadcast feature provides operations between different shape of tensors.

### Tensor + Scalar
- 이건 머 간단하게 전 성분에 스칼라 더해줌

In [26]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])
y = 1

print(x.size())

torch.Size([2, 2])


In [27]:
z = x + y
print(z)
print(z.size())

tensor([[2., 3.],
        [4., 5.]])
torch.Size([2, 2])


### Tensor + Vector

In [30]:
x = torch.FloatTensor([[1, 2],
                       [4, 8]])
y = torch.FloatTensor([3, 5])

print(x.size())
print(y.size())

torch.Size([2, 2])
torch.Size([2])


얘는 마치 y를
[[3, 5],
[3, 5]] 이렇게 보고 더함

In [31]:
z = x + y
print(z)
print(z.size())

tensor([[ 4.,  7.],
        [ 7., 13.]])
torch.Size([2, 2])


In [32]:
x = torch.FloatTensor([[[1, 2]]])
y = torch.FloatTensor([3, 5])

print(x.size())
print(y.size())

torch.Size([1, 1, 2])
torch.Size([2])


In [33]:
z = x + y
print(z)
print(z.size())

tensor([[[4., 7.]]])
torch.Size([1, 1, 2])


### Tensor + Tensor

In [34]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[3],
                       [5]])

print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([2, 1])


In [35]:
z = x + y
print(z)
print(z.size())

tensor([[4., 5.],
        [6., 7.]])
torch.Size([2, 2])


- Note that you need to be careful before using broadcast feature.
- 브로드캐스트 기능 때문에 피보는 경우도 있음

### Failure Case

In [36]:
x = torch.FloatTensor([[[1, 2],
                        [4, 8]]])
y = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

print(x.size())
print(y.size())

z = x + y

torch.Size([1, 2, 2])
torch.Size([3, 3])


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2