## PyTorch Tensor Slicing and Concatenation

In [1]:
import torch

## Slicing and Concatenation

- 자르고 붙이기

### Indexing and Slicing

Prepare target tensor.

In [2]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])
print(x.size())

torch.Size([3, 2, 2])


Access to certain dimension.

In [37]:
print(x[0])
print(x[0, :])
print(x[0, 0, :])
print(x[0, :, 1]) # 얘는 다른 디멘젼에 있는 애들도 가져옴
print(x[0][:][1]) # 다름 

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([1., 2.])
tensor([2., 4.])
tensor([3., 4.])


In [14]:
print(x[-1])
print(x[-1, :])
print(x[-1, :, :])

tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])


In [38]:
print(x[:, 0, :])

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])


Access by range. Note that the number of dimensions would not be changed.

레인지로 그니까 범위로 짜르면 디멘젼이 1이라도 없어지지 않는다

그냥 짜르면 디멘젼 리덕션이 일어남

In [39]:
print(x[1:3, :, :].size())
print(x[:, :1, :].size())
print(x[:, :-1, :].size())

torch.Size([2, 2, 2])
torch.Size([3, 1, 2])
torch.Size([3, 1, 2])


### split: Split tensor to desirable shapes.
- 텐서 자체를 여러개로 쪼갬

In [46]:
x = torch.FloatTensor(10, 4)
x
print(x.size())

torch.Size([10, 4])


In [45]:
splits = x.split(4, dim=0) # 0번 디멘젼이 4개가 되도록 잘라줘
print(splits)
print(type(splits)) # tuple에 담겨서 리턴

for s in splits:
    print(s.size())

(tensor([[4.2488e-05, 6.7137e-07, 6.8993e-07, 2.1627e+23],
        [1.0664e-08, 1.1039e-05, 3.1369e+27, 7.0800e+31],
        [3.1095e-18, 7.7052e+31, 1.9447e+31, 2.0558e+32],
        [1.8755e+28, 3.1093e-18, 1.9421e+31, 2.7491e+20]]), tensor([[2.3078e-12, 1.8179e+31, 1.8524e+28, 9.6695e-06],
        [1.0779e-08, 1.0186e-11, 1.3168e-08, 4.2488e-05],
        [6.7137e-07, 6.8993e-07, 2.1627e+23, 1.0664e-08],
        [1.1966e+22, 3.1097e-18, 6.4805e-10, 6.3007e-10]]), tensor([[4.2481e-05, 7.0264e-04, 2.7094e-09, 6.8240e-07],
        [2.6371e-09, 2.3329e-18, 1.9205e+31, 3.2314e-18]]))
<class 'tuple'>
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


### chunk: Split tensor to number of chunks.

In [51]:
x = torch.FloatTensor(14, 4)

In [52]:
chunks = x.chunk(3, dim=0) #얘는 0번 디멘젼이 텐서를 3개로 잘라줘

for c in chunks:
    print(c.size())

torch.Size([5, 4])
torch.Size([5, 4])
torch.Size([4, 4])


### index_select: Select elements by using dimension index.

In [63]:
x = torch.FloatTensor([[[1, 1],
                        [2, 2]],
                       [[3, 3],
                        [4, 4]],
                       [[5, 5],
                        [6, 6]]])
indice = torch.LongTensor([2, 1])

print(x.size())

torch.Size([3, 2, 2])


In [64]:
y = x.index_select(dim=0, index=indice) # 인덱스는 꼭 텐서가 들어가야하나?

print(y)
print(y.size())

tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 4.]]])
torch.Size([2, 2, 2])


### cat: Concatenation of multiple tensors in the list.

In [74]:
x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
y = torch.FloatTensor([[10, 11, 12],
                       [13, 14, 15],
                       [16, 17, 18]])

In [75]:
z = torch.cat([x, y], dim=0) # 0번디멘젼으로 붙여줘, 0번 디멘젼 사이즈를 더해줘
print(z)
print(z.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
torch.Size([6, 3])


In [76]:
z = torch.cat([x, y], dim=-1) # 맨 뒤 디멘젼으로 붙여줘
print(z)
print(z.size())

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])
torch.Size([3, 6])


### stack: Stacking of multiple tensors in the list.

In [77]:
z = torch.stack([x, y]) # 차원이 하나 더 생김
print(z)
print(z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


Or you can specify the dimension. Default is 0.

In [78]:
z = torch.stack([x, y], dim=-1) #얘는 맨 뒤에 차원이 하나 더 생기는거
print(z)
print(z.size())

tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]])
torch.Size([3, 3, 2])


### Implement 'stack' function by using 'cat'.

In [81]:
# z = torch.stack([x, y])
z = torch.cat([x.unsqueeze(0), y.unsqueeze(0)], dim=0)
print(z)
print(z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


### Useful Trick: Merge results from iterations

In [82]:
result = []
for i in range(5):
    x = torch.FloatTensor(2, 2)
    result += [x] # 2 x 2가 다섯개 들어감

result = torch.stack(result) #그걸 쌓으니까 5 x 2 x 2
result.size()

torch.Size([5, 2, 2])