# How to use GPU

In [1]:
import torch
import torch.nn as nn

## Convert to CUDA tensor: cuda()

텐서를 cpu로 연산하면 ram메모리에 할당

텐서를 gpu로 연산하면 해당 gpu의 메모리에 할당

같은 디바이스의 텐서끼리만 연산이 가능하다!!

In [2]:
x = torch.cuda.FloatTensor(2, 2)    

x

TypeError: type torch.cuda.FloatTensor not available. Torch not compiled with CUDA enabled.

In [6]:
x = torch.FloatTensor(2, 2)

x

tensor([[9.2755e-39, 1.0561e-38],
        [6.9796e-39, 9.8266e-39]])

In [7]:
x.cuda()

AssertionError: Torch not compiled with CUDA enabled

In [8]:
d = torch.device('cuda:0')

In [9]:
x.cuda(device=d)

AssertionError: Torch not compiled with CUDA enabled

In [10]:
x.device

device(type='cpu')

## Convert to CUDA tensor: to()

In [11]:
x.to(device=d)

AssertionError: Torch not compiled with CUDA enabled

## Convert to CPU tensor from CUDA tensor

In [12]:
x = torch.cuda.FloatTensor(2, 2)

TypeError: type torch.cuda.FloatTensor not available. Torch not compiled with CUDA enabled.

In [13]:
x = x.cpu()

In [14]:
d = torch.device('cpu')
x = x.to(d)

## Move model from CPU to GPU.

In [15]:
def print_params(model):
    for p in model.parameters():
        print(p)

In [24]:
linear = nn.Linear(2, 2)

print_params(linear)

Parameter containing:
tensor([[-0.1969,  0.0700],
        [ 0.5826, -0.2269]], requires_grad=True)
Parameter containing:
tensor([ 0.5231, -0.4706], requires_grad=True)


In [25]:
linear = linear.cuda()

print_params(linear)

AssertionError: Torch not compiled with CUDA enabled

In [26]:
linear = linear.cpu()

print_params(linear)

Parameter containing:
tensor([[-0.1969,  0.0700],
        [ 0.5826, -0.2269]], requires_grad=True)
Parameter containing:
tensor([ 0.5231, -0.4706], requires_grad=True)


In [27]:
d = torch.device('cuda:0')
linear = linear.to(d)

print_params(linear)

AssertionError: Torch not compiled with CUDA enabled

Note that nn.Module class does not have 'device' property.

In [28]:
linear.device

AttributeError: 'Linear' object has no attribute 'device'

## Tricks

In [18]:
x = torch.cuda.FloatTensor(2, 2)

In [19]:
x.new(2, 2)

tensor([[2.3694e-38, 1.2422e-01],
        [1.4013e-45, 0.0000e+00]], device='cuda:0')

In [20]:
torch.zeros_like(x)

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [21]:
torch.ones_like(x)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [22]:
list(linear.parameters())[0].new(2, 2)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')